[build]
  publish = "."
  command = "echo 'window.API_BASE_URL = \"$API_BASE_URL\";' > env.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  # ngrok URL을 여기에 설정하세요
  # API_BASE_URL = "https://your-ngrok-url.ngrok-free.app" 